### ISSUE TITLE
RSpec block length

### ISSUE THREAD

**Issue by benlangfeld** [powerhome/power_linting#8]
It is common for rspec tests to violate `Metrics/BlockLength` because of the `describe`/`context` DSL. [In NitroID](https://github.com/powerhome/nitro-id/blob/main/authentication_service/.rubocop.yml#L9-L12) we disable this cop like so:

```yaml
Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context
```

It would be nice for `rubocop-powerhome` to contemplate this.

@xjunior suggested `RSpec.describe`/`RSpec.context` explicitly here but that doesn't work unless the specs are also explicit, for which there would then also need to be a cop to encourage devs to adopt.
